language: go

os:
  - linux
  - osx

before_install:
  # Setup dependency management tool
  - mkdir $GOBIN
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

go:
  - "1.9"
  - master