language: go

os:
  - linux
  - osx

before_install:
  # Setup dependency management tool
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GOBIN=$GOPATH/bin ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir "$GOBIN" ; fi
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

go:
  - "1.9"
  - master